name: Update README

on:
  schedule:
    - cron: "0 0 * * *" # Runs every day at midnight
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Fetch GitHub Stats
        env:
          GH_USERNAME: "your-username"  # Replace with your GitHub username
        run: |
          COMMIT_COUNT=$(curl -s https://api.github.com/users/$GH_USERNAME | jq '.public_repos')
          PR_COUNT=$(curl -s https://api.github.com/search/issues?q=author:$GH_USERNAME+type:pr | jq '.total_count')
          MERGED_COUNT=$(curl -s https://api.github.com/search/issues?q=
